# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bae51cd0abec1aa788c1909c115a86cefd474b0f6fe9d9428dfd5d7692040f9c187f9f1025f53fbf12cfbc2639f1f4eb6f3f34fddb98f0af6f5a98a2bdc33e21

test:
  secret_key_base: aa421366bd8c22369ea5ab65f3678579e3a85dbb0cf524fe113861e4dfc79c8743944aab75172e4e71ee0a9a7f79351c78adbb48846e3ee47c02c6c7fbb7c1e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
